name: prime_number
description: Tub sonlarni ajratib beruvchi package
version: 0.0.1
homepage: https://github.com/Islombek885/prime_number

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

repository: https://github.com/Islombek885/prime_number
